spring:
  application:
    name: TrackingNumberGenerator

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://dpg-d19d9eh5pdvs73e8ld2g-a.oregon-postgres.render.com/database_tracking_ijhd
#    url: jdbc:postgresql://dpg-crb87dlsvqrc73eu2fj0-a.oregon-postgres.render.com:5432/database_tracking
    username: database_tracking_user
    password: gszA5bhFyHXxWcxlkSomFY1DQ89uGoVa

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8182

swagger:
  server-url: https://gajanan-trackingnumbergenerator.onrender.com
